import { BusinessCard } from "./types";
import { v4 as uuid } from 'uuid'

export const defaultCards: BusinessCard[] = [
    {
        title: "John's Computer Repair",
        subtitle: "Computer Technician",
        description: "John's Computer Repair provides expert computer repair services in Tel Aviv. With years of experience, we specialize in diagnosing and fixing various computer issues, including hardware and software problems. Our team of skilled technicians is dedicated to providing prompt and reliable service to ensure your computer is up and running smoothly. Contact us today for all your computer repair needs.",
        phone: "0532456683",
        email: "John@gmail.com",
        web: "JohnSite.com",
        imageUrl: "https://images.pexels.com/photos/10558599/pexels-photo-10558599.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        imageAlt: "Computer Repair Shop",
        country: "Israel",
        city: "Tel Aviv",
        street: "Dizengoff",
        houseNumber: '12',
        zip: '12345',
        _id: uuid()
    },
    {
        title: "David's Plumbing Services",
        subtitle: "Plumber",
        description: "David's Plumbing Services offers top-quality plumbing solutions in Jerusalem. Our team of licensed plumbers is experienced in handling a wide range of plumbing needs, from minor repairs to full system installations. We pride ourselves on delivering exceptional customer service and ensuring customer satisfaction. Whether you have a leaky faucet or need a complete plumbing overhaul, trust Amy's Plumbing Services for reliable and efficient plumbing solutions.",
        phone: "0556543210",
        email: "David@gmail.com",
        web: "DavidSite.com",
        imageUrl: "https://plus.unsplash.com/premium_photo-1663011056778-2b987e47434a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
        imageAlt: "Plumbing Services",
        country: "Israel",
        city: "Jerusalem",
        street: "King George",
        houseNumber: '45',
        zip: '54321',
        _id: uuid()
    },
    {
        title: "Mike's Electrician Services",
        subtitle: "Electrician",
        description: "Mike's Electrician Services is your go-to electrician in Haifa. We provide a wide range of electrical services for both residential and commercial customers. From electrical installations to repairs and maintenance, our skilled electricians deliver reliable and efficient solutions. We prioritize safety and adhere to industry standards to ensure your electrical systems are in optimal condition. Count on Mike's Electrician Services for all your electrical needs in Haifa and surrounding areas.",
        phone: "0521743333",
        email: "Mike@gmail.com",
        web: "MikeSite.com",
        imageUrl: "https://plus.unsplash.com/premium_photo-1682086494838-6410429123a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
        imageAlt: "Electrician Services",
        country: "Israel",
        city: "Hadera",
        street: "Rothschild Boulevard",
        houseNumber: '17',
        zip: '67890',
        _id: uuid()
    },
    {
        title: "Sarah's Cleaning Company",
        subtitle: "Cleaning Services",
        description: "Sarah's Cleaning Company offers professional cleaning services in Netanya. We specialize in providing comprehensive cleaning solutions for homes and offices. Our dedicated team of cleaners is trained to deliver exceptional results and ensure a clean and healthy environment. Whether you need regular cleaning, deep cleaning, or move-in/move-out cleaning, Sarah's Cleaning Company is committed to exceeding your expectations. Experience the difference with our reliable and efficient cleaning services.",
        phone: "0535251866",
        email: "Sarah@gmail.com",
        web: "SarahSite.com",
        imageUrl: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
        imageAlt: "Cleaning Company",
        country: "Israel",
        city: "Netanya",
        street: "Herzl",
        houseNumber: '56',
        zip: '98765',
        _id: uuid()
    },
    {
        title: "Rachel's Graphic Design",
        subtitle: "Graphic Designer",
        description: "Rachel's Graphic Design offers creative and professional graphic design services. We specialize in logo design, branding, and marketing materials. Our goal is to help businesses stand out with visually appealing and impactful designs. Contact us today to discuss your design needs.",
        phone: "0549876543",
        email: "rachel@gmail.com",
        web: "racheldesign.com",
        imageUrl: "https://images.pexels.com/photos/933255/pexels-photo-933255.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        imageAlt: "Graphic Design",
        country: "Israel",
        city: "Tel Aviv",
        street: "Rothschild",
        houseNumber: '123',
        zip: '54321',
        _id: uuid()
    },
    {
        title: "Mark's Photography Studio",
        subtitle: "Photographer",
        description: "Mark's Photography Studio provides professional photography services for various occasions. From weddings and events to portraits and commercial photography, we capture moments with creativity and precision. Trust us to deliver stunning images that tell your story. Contact us to book a session or discuss your photography needs.",
        phone: "0501234567",
        email: "mark@gmail.com",
        web: "markphotography.com",
        imageUrl: "https://images.pexels.com/photos/1728163/pexels-photo-1728163.jpeg",
        imageAlt: "Photography Studio",
        country: "Israel",
        city: "Jerusalem",
        street: "Allenby",
        houseNumber: '789',
        zip: '98765',
        _id: uuid()
    },
    {
        title: "Alex's Fitness Training",
        subtitle: "Personal Trainer",
        description: "Alex's Fitness Training offers personalized fitness programs and training sessions. Whether your goal is to lose weight, build muscle, or improve overall fitness, we provide expert guidance and motivation. Let us help you reach your fitness goals and transform your lifestyle. Contact us to get started on your fitness journey.",
        phone: "0587654321",
        email: "alex@gmail.com",
        web: "alexfitness.com",
        imageUrl: "https://images.pexels.com/photos/2011377/pexels-photo-2011377.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        imageAlt: "Fitness Training",
        country: "Israel",
        city: "Haifa",
        street: "Herzl",
        houseNumber: '456',
        zip: '12345',
        _id: uuid()
    },
    {
        title: "Sophie's Bakery",
        subtitle: "Baker",
        description: "Sophie's Bakery specializes in delicious homemade baked goods. From bread and pastries to cakes and cookies, our treats are made with love and quality ingredients. Order custom cakes for special occasions or drop by our bakery for a fresh selection. Indulge in the delightful flavors of Sophie's Bakery.",
        phone: "0523456789",
        email: "sophie@gmail.com",
        web: "sophiebakery.com",
        imageUrl: "https://images.pexels.com/photos/3218467/pexels-photo-3218467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        imageAlt: "Bakery",
        country: "Israel",
        city: "Tel Aviv",
        street: "Ben Yehuda",
        houseNumber: '789',
        zip: '54321',
        _id: uuid()
    }
];
