import { BusinessCard } from "./types";

export const defaultCards: BusinessCard[] = [
    {
        title: "Acme Corporation",
        subtitle: "Leading Provider of Widgets",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        phone: "0554567890",
        email: "info@acmecorp.com",
        web: "https://www.acmecorp.com",
        imageUrl: "https://example.com/business1.jpg",
        imageAlt: "Acme Corporation Logo",
        state: "California",
        country: "United States",
        city: "Los Angeles",
        street: "Main Street",
        houseNumber: 123,
        zip: 12345,
    },
    {
        title: "XYZ Industries",
        subtitle: "Innovative Solutions for All Industries",
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
        phone: "0554567890",
        email: "info@xyzindustries.com",
        web: "https://www.xyzindustries.com",
        imageUrl: "https://example.com/business2.jpg",
        imageAlt: "XYZ Industries Logo",
        state: "New York",
        country: "United States",
        city: "New York City",
        street: "Elm Street",
        houseNumber: 456,
        zip: 54321,
    },
    {
        title: "GlobeTech Solutions",
        subtitle: "Technology Consulting and Services",
        description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur.",
        phone: "0554567890",
        email: "info@globetech.com",
        web: "https://www.globetech.com",
        imageUrl: "https://example.com/business3.jpg",
        imageAlt: "GlobeTech Solutions Logo",
        state: "Texas",
        country: "United States",
        city: "Houston",
        street: "Oak Street",
        houseNumber: 789,
        zip: 67890,
    },
    {
        title: "Apex Solutions",
        subtitle: "Your Partner for Success",
        description: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit.",
        phone: "0554567890",
        email: "info@apexsolutions.com",
        web: "https://www.apexsolutions.com",
        imageUrl: "https://example.com/business4.jpg",
        imageAlt: "Apex Solutions Logo",
        state: "Florida",
        country: "United States",
        city: "Miami",
        street: "Pine Street",
        houseNumber: 567,
        zip: 98765,
    },
];
